<?php
/**
 * Plugin Name:  DTRT Plugin
 * Plugin URI:   https://github.com/dotherightthing/wpdtrt-generated-plugin
 * Description:  A plugin generated by DTRT WordPress Plugin Boilerplate Generator,
which piggybacks on the functionality within DTRT WordPress Plugin Boilerplate.
 * Version:      0.12.345
 * Author:       Dan Smith
 * Author URI:   https://profiles.wordpress.org/dotherightthingnz
 * License:      GPLv2 or later
 * License URI:  http://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:  wpdtrt-generated-plugin
 * Domain Path:  /languages
 */

if( ! defined( 'WPDTRT_PLUGIN_VERSION' ) ) {
  define( 'WPDTRT_PLUGIN_VERSION', '0.12.345' );
}

function wpdtrt_plugin_shortcode_1_init() {
  $wpdtrt_plugin_shortcode_1 = new WPDTRT_Plugin_Shortcode();
}

function wpdtrt_plugin_shortcode_2_init() {
  $wpdtrt_plugin_shortcode_2 = new WPDTRT_Plugin_Shortcode();
}

function wpdtrt_plugin_shortcode_3_init() {
  $wpdtrt_plugin_shortcode_3 = new WPDTRT_Plugin_Shortcode();
}

?>
